# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\garage\ui\test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 403)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 941, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(380, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0,0,0);")
        self.label.setObjectName("label")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 40, 901, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(9)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 250, 901, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RoutePrintButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RoutePrintButton.setFont(font)
        self.RoutePrintButton.setStyleSheet("")
        self.RoutePrintButton.setObjectName("RoutePrintButton")
        self.horizontalLayout_4.addWidget(self.RoutePrintButton)
        self.RouteCreateButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RouteCreateButton.setFont(font)
        self.RouteCreateButton.setStyleSheet("")
        self.RouteCreateButton.setObjectName("RouteCreateButton")
        self.horizontalLayout_4.addWidget(self.RouteCreateButton)
        self.RouteUpdateButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RouteUpdateButton.setFont(font)
        self.RouteUpdateButton.setStyleSheet("")
        self.RouteUpdateButton.setObjectName("RouteUpdateButton")
        self.horizontalLayout_4.addWidget(self.RouteUpdateButton)
        self.RouteDeleteButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RouteDeleteButton.setFont(font)
        self.RouteDeleteButton.setStyleSheet("")
        self.RouteDeleteButton.setObjectName("RouteDeleteButton")
        self.horizontalLayout_4.addWidget(self.RouteDeleteButton)
        self.RouteSearchButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RouteSearchButton.setFont(font)
        self.RouteSearchButton.setStyleSheet("")
        self.RouteSearchButton.setObjectName("RouteSearchButton")
        self.horizontalLayout_4.addWidget(self.RouteSearchButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 250, 901, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AvtoPrintButton = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AvtoPrintButton.setFont(font)
        self.AvtoPrintButton.setStyleSheet("")
        self.AvtoPrintButton.setObjectName("AvtoPrintButton")
        self.horizontalLayout_2.addWidget(self.AvtoPrintButton)
        self.AvtoCreateButton = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AvtoCreateButton.setFont(font)
        self.AvtoCreateButton.setStyleSheet("")
        self.AvtoCreateButton.setObjectName("AvtoCreateButton")
        self.horizontalLayout_2.addWidget(self.AvtoCreateButton)
        self.AvtoUpdateButton = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AvtoUpdateButton.setFont(font)
        self.AvtoUpdateButton.setStyleSheet("")
        self.AvtoUpdateButton.setObjectName("AvtoUpdateButton")
        self.horizontalLayout_2.addWidget(self.AvtoUpdateButton)
        self.AvtoDeleteButton = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AvtoDeleteButton.setFont(font)
        self.AvtoDeleteButton.setStyleSheet("")
        self.AvtoDeleteButton.setObjectName("AvtoDeleteButton")
        self.horizontalLayout_2.addWidget(self.AvtoDeleteButton)
        self.AvtoSearchButton = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AvtoSearchButton.setFont(font)
        self.AvtoSearchButton.setStyleSheet("")
        self.AvtoSearchButton.setObjectName("AvtoSearchButton")
        self.horizontalLayout_2.addWidget(self.AvtoSearchButton)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 901, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(380, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 250, 901, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DriverPrintButton = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DriverPrintButton.setFont(font)
        self.DriverPrintButton.setStyleSheet("")
        self.DriverPrintButton.setObjectName("DriverPrintButton")
        self.horizontalLayout.addWidget(self.DriverPrintButton)
        self.DriverCreateButton = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DriverCreateButton.setFont(font)
        self.DriverCreateButton.setStyleSheet("")
        self.DriverCreateButton.setObjectName("DriverCreateButton")
        self.horizontalLayout.addWidget(self.DriverCreateButton)
        self.DriverUpdateButton = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DriverUpdateButton.setFont(font)
        self.DriverUpdateButton.setStyleSheet("")
        self.DriverUpdateButton.setObjectName("DriverUpdateButton")
        self.horizontalLayout.addWidget(self.DriverUpdateButton)
        self.DriverDeleteButton = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DriverDeleteButton.setFont(font)
        self.DriverDeleteButton.setStyleSheet("")
        self.DriverDeleteButton.setObjectName("DriverDeleteButton")
        self.horizontalLayout.addWidget(self.DriverDeleteButton)
        self.DriverSearchButton = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DriverSearchButton.setFont(font)
        self.DriverSearchButton.setStyleSheet("")
        self.DriverSearchButton.setObjectName("DriverSearchButton")
        self.horizontalLayout.addWidget(self.DriverSearchButton)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 40, 901, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 250, 901, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.UserPrintButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserPrintButton.setFont(font)
        self.UserPrintButton.setStyleSheet("")
        self.UserPrintButton.setObjectName("UserPrintButton")
        self.horizontalLayout_3.addWidget(self.UserPrintButton)
        self.UserCreateButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserCreateButton.setFont(font)
        self.UserCreateButton.setStyleSheet("")
        self.UserCreateButton.setObjectName("UserCreateButton")
        self.horizontalLayout_3.addWidget(self.UserCreateButton)
        self.UserUpdateButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserUpdateButton.setFont(font)
        self.UserUpdateButton.setStyleSheet("")
        self.UserUpdateButton.setObjectName("UserUpdateButton")
        self.horizontalLayout_3.addWidget(self.UserUpdateButton)
        self.UserDeleteButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserDeleteButton.setFont(font)
        self.UserDeleteButton.setStyleSheet("")
        self.UserDeleteButton.setObjectName("UserDeleteButton")
        self.horizontalLayout_3.addWidget(self.UserDeleteButton)
        self.UserSearchButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserSearchButton.setFont(font)
        self.UserSearchButton.setStyleSheet("")
        self.UserSearchButton.setObjectName("UserSearchButton")
        self.horizontalLayout_3.addWidget(self.UserSearchButton)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(360, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 40, 901, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setStyleSheet("")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Гараж"))
        self.tab.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Выезды</p></body></html>"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "начало"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "конец"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "план"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "исполнено"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "заказчик"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Учетный номер"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Имя водителя"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Номер водителя"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "id"))
        self.RoutePrintButton.setText(_translate("MainWindow", "Печать"))
        self.RouteCreateButton.setText(_translate("MainWindow", "Новая запись"))
        self.RouteUpdateButton.setText(_translate("MainWindow", "Обновить"))
        self.RouteDeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.RouteSearchButton.setText(_translate("MainWindow", "Поиск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Выезды"))
        self.AvtoPrintButton.setText(_translate("MainWindow", "Печать"))
        self.AvtoCreateButton.setText(_translate("MainWindow", "Новая запись"))
        self.AvtoUpdateButton.setText(_translate("MainWindow", "Обновить"))
        self.AvtoDeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.AvtoSearchButton.setText(_translate("MainWindow", "Поиск"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "марка"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "номер гос регистрации"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "год выпуска"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Учетный номер"))
        self.label_2.setText(_translate("MainWindow", "Автомобили"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Автомобили"))
        self.label_3.setText(_translate("MainWindow", "Водители"))
        self.DriverPrintButton.setText(_translate("MainWindow", "Печать"))
        self.DriverCreateButton.setText(_translate("MainWindow", "Новая запись"))
        self.DriverUpdateButton.setText(_translate("MainWindow", "Обновить"))
        self.DriverDeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.DriverSearchButton.setText(_translate("MainWindow", "Поиск"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "имя"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "возраст"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "опыт"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "зарплата"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Номер водителя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Водители"))
        self.UserPrintButton.setText(_translate("MainWindow", "Печать"))
        self.UserCreateButton.setText(_translate("MainWindow", "Новая запись"))
        self.UserUpdateButton.setText(_translate("MainWindow", "Обновить"))
        self.UserDeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.UserSearchButton.setText(_translate("MainWindow", "Поиск"))
        self.label_4.setText(_translate("MainWindow", "Пользователи"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "должность"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Логин"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Пароль"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Имя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Пользователи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

