UPDATE garage.driver SET name = 'Михаил', old = 45, experience = 10, payment = 3000 WHERE id = 1;
UPDATE garage.driver SET name = 'Лена', old = 22, experience = 1, payment = 15000 WHERE id = 2;
UPDATE garage.driver SET name = 'Аурелия Козлова', old = 66, experience = 10, payment = 16858 WHERE id = 6;
UPDATE garage.driver SET name = 'Лада Шашкова', old = 23, experience = 3, payment = 20416 WHERE id = 7;
UPDATE garage.driver SET name = 'Ростислава Кулакова', old = 62, experience = 5, payment = 10482 WHERE id = 8;
UPDATE garage.driver SET name = 'Анисья Филиппова', old = 44, experience = 5, payment = 15332 WHERE id = 9;
UPDATE garage.driver SET name = 'Илзе Семёнова', old = 35, experience = 4, payment = 20817 WHERE id = 10;
UPDATE garage.driver SET name = 'Инара Егорова', old = 36, experience = 4, payment = 10060 WHERE id = 11;
UPDATE garage.driver SET name = 'Софья Александрова', old = 25, experience = 10, payment = 13062 WHERE id = 12;
UPDATE garage.driver SET name = 'Земфира Дмитриева', old = 50, experience = 3, payment = 25434 WHERE id = 13;